name: Bug report
description: Report a defect or regression affecting sswg-mvm behavior
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug report

        Use this form to report **defects, regressions, or incorrect behavior**.
        Please provide enough detail to allow deterministic reproduction where applicable.

  - type: textarea
    id: bug_description
    attributes:
      label: Description of the bug
      description: Clearly describe the observed behavior and what is incorrect.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: Provide exact, ordered steps to reproduce the issue.
      placeholder: |
        1. Run command or workflow ...
        2. Provide input ...
        3. Observe output ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen instead.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide relevant environment details (OS, Python version, runtime, etc.).
      placeholder: |
        - OS:
        - Python version:
        - Runtime / CI:
        - Other relevant context:

  - type: dropdown
    id: affected_layer
    attributes:
      label: Affected repository layer
      description: Select the primary layer impacted.
      options:
        - schemas/
        - pdl/
        - generator/
        - cli/
        - reproducibility/
        - modules/
        - docs/
        - Other

  - type: checkboxes
    id: affected_phases
    attributes:
      label: Affected pipeline phase(s)
      description: Select all phases impacted by this bug.
      options:
        - label: ingest
        - label: normalize
        - label: parse
        - label: analyze
        - label: generate
        - label: validate
        - label: compare
        - label: interpret
        - label: log

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Include logs, screenshots, error messages, or other relevant details.
