#!/usr/bin/env python3
"""
ai_visualization/export_manager.py
Grimoire v4.5 — Workflow Export Module

Handles export of generated workflows into multiple human- and machine-readable
formats: Graphviz (.dot), JSON (.json), and Markdown (.md).

Supports the --export flag in cli.py:
    --export json        → saves JSON only
    --export markdown    → saves Markdown only
    --export both        → saves both JSON + Markdown (default includes .dot)
"""

import os
import json
from datetime import datetime


# ---------------------- GRAPHVIZ EXPORT ---------------------- #


def export_graphviz(wf: dict, out_dir: str = "./build") -> str:
    """Export the workflow dependency graph to a Graphviz DOT file."""
    os.makedirs(out_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(out_dir, f"workflow_graph_{timestamp}.dot")

    graph = wf.get("dependency_graph", {})
    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("digraph workflow {\n")
        f.write(
            '  rankdir=LR;\n  node [shape=box, style="rounded,filled", color="#7C3AED", fillcolor="#EDE9FE"];\n'
        )
        for n in nodes:
            f.write(f'  "{n}" [label="{n}"];\n')
        for e in edges:
            if len(e) == 2:
                f.write(f'  "{e[0]}" -> "{e[1]}";\n')
        f.write("}\n")

    return out_path


# ---------------------- MARKDOWN EXPORT ---------------------- #


def export_markdown(wf: dict, out_dir: str = "./build") -> str:
    """Generate a human-readable Markdown version of the workflow."""
    os.makedirs(out_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(
        out_dir, f"workflow_{wf.get('workflow_id', 'unknown')}_{timestamp}.md"
    )

    md_lines = []
    md_lines.append(f"# Workflow: {wf.get('workflow_id', 'Untitled')}")
    md_lines.append("")
    md_lines.append(f"**Version:** {wf.get('version', 'N/A')}")
    md_lines.append(f"**Purpose:** {wf.get('metadata', {}).get('purpose', 'N/A')}")
    md_lines.append(f"**Audience:** {wf.get('metadata', {}).get('audience', 'N/A')}")
    md_lines.append("")
    md_lines.append("## Phases")
    md_lines.append("")

    for phase in wf.get("phases", []):
        md_lines.append(f"### {phase.get('title', 'Untitled Phase')}")
        if "tasks" in phase:
            for task in phase["tasks"]:
                md_lines.append(f"- {task}")
        if "ai_task_logic" in phase:
            md_lines.append("")
            md_lines.append("**AI Logic:**")
            md_lines.append(f"> {phase['ai_task_logic']}")
        md_lines.append("")

    md_lines.append("---")
    md_lines.append(f"*Generated by Grimoire v4.5 on {timestamp}*")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines))

    return out_path


# ---------------------- JSON EXPORT ---------------------- #


def export_json(wf: dict, out_dir: str = "./build") -> str:
    """Save the workflow as a structured JSON file."""
    os.makedirs(out_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(
        out_dir, f"workflow_{wf.get('workflow_id', 'unknown')}_{timestamp}.json"
    )

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(wf, f, indent=2)

    return out_path


# ---------------------- MULTI-MODE EXPORT ---------------------- #


def export_workflow(wf: dict, export_mode: str = "json") -> dict:
    """
    Export workflow according to CLI export mode.
    Supported modes:
        - 'json'
        - 'markdown'
        - 'both'
    Always generates a .dot file for visualization.
    """
    results = {}

    # Always export Graphviz diagram
    results["graphviz"] = export_graphviz(wf)

    if export_mode == "json":
        results["json"] = export_json(wf)

    elif export_mode == "markdown":
        results["markdown"] = export_markdown(wf)

    elif export_mode == "both":
        results["json"] = export_json(wf)
        results["markdown"] = export_markdown(wf)

    else:
        raise ValueError(f"Invalid export mode: {export_mode}")

    return results
