#!/usr/bin/env python3
"""
ai_visualization/markdown_importer.py
Grimoire v4.6 — Markdown Import Parser

This module parses Markdown (.md) instructional files generated by the system
and reconstructs them into structured workflow JSON dictionaries.

It enables bidirectional knowledge transfer:
    - Markdown → JSON  (for reprocessing, validation, or regeneration)
    - JSON → Markdown  (via export_manager.py)
"""

import os
import re
import json
from datetime import datetime


def parse_markdown(md_path: str) -> dict:
    """Convert a Markdown workflow file into a JSON-compatible structure."""
    if not os.path.exists(md_path):
        raise FileNotFoundError(f"Markdown file not found: {md_path}")

    with open(md_path, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f.readlines() if line.strip()]

    workflow = {
        "workflow_id": None,
        "version": None,
        "metadata": {},
        "phases": [],
        "dependency_graph": {"nodes": [], "edges": []},
    }

    current_phase = None
    for i, line in enumerate(lines):
        # Workflow title
        if line.startswith("# "):
            workflow["workflow_id"] = re.sub(r"^#\s*Workflow:\s*", "", line)

        # Metadata fields
        elif line.startswith("**Version:**"):
            workflow["version"] = line.split("**Version:**")[-1].strip()
        elif line.startswith("**Purpose:**"):
            workflow["metadata"]["purpose"] = line.split("**Purpose:**")[-1].strip()
        elif line.startswith("**Audience:**"):
            workflow["metadata"]["audience"] = line.split("**Audience:**")[-1].strip()

        # Phase title
        elif line.startswith("### "):
            if current_phase:
                workflow["phases"].append(current_phase)
            current_phase = {"title": line[4:], "tasks": []}

        # Task line
        elif line.startswith("- "):
            if current_phase is not None:
                task_text = line[2:]
                current_phase["tasks"].append(task_text)
                workflow["dependency_graph"]["nodes"].append(task_text)

        # AI logic block
        elif line.startswith("> "):
            if current_phase is not None:
                logic_text = line[2:]
                current_phase.setdefault("ai_task_logic", "")
                current_phase["ai_task_logic"] += logic_text + " "

    # Append last phase if not empty
    if current_phase:
        workflow["phases"].append(current_phase)

    # Basic ID and fallback handling
    if not workflow["workflow_id"]:
        base_name = os.path.basename(md_path).replace(".md", "")
        workflow["workflow_id"] = f"imported_{base_name}"

    if not workflow["version"]:
        workflow["version"] = "Imported"

    # Generate simple edge map (linear sequence)
    nodes = workflow["dependency_graph"]["nodes"]
    workflow["dependency_graph"]["edges"] = [
        [nodes[i], nodes[i + 1]] for i in range(len(nodes) - 1)
    ]

    return workflow


def import_markdown(md_path: str, out_dir: str = "./data/workflows") -> str:
    """Parse Markdown and save as structured JSON."""
    wf = parse_markdown(md_path)
    os.makedirs(out_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = os.path.join(out_dir, f"{wf['workflow_id']}_{timestamp}.json")

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(wf, f, indent=2)

    print(f"🪶 Imported Markdown workflow saved as JSON → {out_path}")
    return out_path
